name: Database Deploy

on:
  push:
    branches:
      - main
env:
  NODE_VERSION: '22.x'
jobs:
  code:
    name: install code
    runs-on: ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: generate prisma client
        run: npx run generate
      - name: run migration
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
      - name: Migration completed
        run: echo "Database migration finished successfully"
